// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axkwjypiajieiwnhedsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4a3dqeXBpYWppZWl3bmhlZHNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc0NjUxMzMsImV4cCI6MjA1MzA0MTEzM30.WJSXVYNCzkrZ3Q7UhEgw4XSWltz1nzv8ZvNpcHi8zrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);